# Generated by Django 2.2.5 on 2019-10-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='welcome_message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
