# Generated by Django 2.2.5 on 2019-10-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191017_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='welcome_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
